apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n5l81te5g-java-springboot
  janus-idp.io/tekton: n5l81te5g-java-springboot
  backstage.io/kubernetes-id: n5l81te5g-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n5l81te5g-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
